src/Entity/Task.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Enums\Task\TaskState;
use App\Repository\TaskRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: "tasks")]
#[ORM\Entity(repositoryClass: TaskRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Task
{
    use Timestampable;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: "task_state", length: 255, options: ["default" => "CREATED"])]
    private ?TaskState $state = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Project $project = null;

    #[ORM\ManyToOne(inversedBy: 'tasksCreated')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'task', targetEntity: TaskComment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: user::class, inversedBy: 'tasksAssigned')]
    private Collection $assigned_users;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->assigned_users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getState(): ?TaskState
    {
        return $this->state;
    }

    public function setState(?TaskState $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): static
    {
        $this->project = $project;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, TaskComment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(TaskComment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTask($this);
        }

        return $this;
    }

    public function removeComment(TaskComment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTask() === $this) {
                $comment->setTask(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, user>
     */
    public function getAssignedUsers(): Collection
    {
        return $this->assigned_users;
    }

    public function addAssignedUser(user $assignedUser): static
    {
        if (!$this->assigned_users->contains($assignedUser)) {
            $this->assigned_users->add($assignedUser);
        }

        return $this;
    }

    public function removeAssignedUser(user $assignedUser): static
    {
        $this->assigned_users->removeElement($assignedUser);

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use App\Entity\User;
use App\Enums\Task\TaskState;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class TaskType extends AbstractType
{
    public function __construct(protected RequestStack $requestStack)
    {}

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $request = $this->requestStack->getCurrentRequest();

        $projectId = $request->attributes->get('id');

        $builder
            ->add('name', TextType:: class, [
                'constraints' => [
                    new NotBlank,
                    new Length(['min' => 5])
                ]
            ])
            ->add('description', TextareaType::class, [
                'constraints' => [
                    new NotBlank,
                    new Length(['min' => 15])
                ]
            ])
            ->add('state', EnumType::class, [
                'class' => TaskState::class,
                'choice_label' => function ($choice) {
                    return $choice->toString();
                }
            ])
            ->add('assigned_users', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
                'query_builder' => function(UserRepository $userRepo) use ($projectId) {
                    return $userRepo->getTeamForProjectQuery($projectId);
                },
                'required' => false,
                'multiple' => true,
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Enums\Task\TaskState;
use App\Form\CommentType;
use App\Form\TaskType;
use App\Repository\ProjectRepository;
use App\Repository\TaskCommentRepository;
use App\Repository\TaskRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TaskController extends AbstractController
{
    #[Route('/project/{id<[0-9]+>}/addTask', name: 'app_task_create', methods: ["GET", "POST"])]
    public function create(int $id, Request $request, TaskRepository $taskRepo, ProjectRepository $projectRepo): Response
    {
        $form = $this->createForm(TaskType::class);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $task = $form->getData();

            $project = $projectRepo->find($id);

            $task
                ->setState(TaskState::CREATED)
                ->setProject($project);

            $taskRepo->save($task, true);
            
            $this->addFlash('success', 'Your task has been added to the project !');

            return $this->redirectToRoute('app_project_show', ['id' => $id]);
        }

        return $this->render('task/create.html.twig', ['form' => $form, 'projectId' => $id]);
    }

    #[Route('/task/{taskId<[0-9]+>}', name: 'app_task_show', methods: ["GET", "POST"])]
    public function show(int $taskId, Request $request, TaskRepository $taskRepo, TaskCommentRepository $commentRepo)
    {
        $task = $taskRepo->find($taskId);

        // Form allowing to comment the current task
        $form = $this->createForm(CommentType::class);

        $form->handleRequest($request);

        if($this->getUser() && $form->isSubmitted() && $form->isValid())
        {
            $comment = $form->getData();

            $comment->setAuthor($this->getUser());
            $comment->setTask($task);

            $commentRepo->save($comment, true);

            $this->addFlash('success', 'Your comment has been added !');

            return $this->redirectToRoute('app_task_show', ['taskId' => $task->getId()]);
        }

        return $this->render('task/show.html.twig', compact('task', 'form'));
    }

    #[Route('/task/{id<[0-9]+>}/edit', name: 'app_task_edit', methods: ["GET", "PUT"])]
    public function edit(int $id, Request $request, TaskRepository $taskRepo)
    {
        $task = $taskRepo->find($id);

        $form = $this->createForm(TaskType::class, $task, [ 'method' => 'PUT']);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $taskRepo->save($task, true);

            $this->addFlash('success', 'The task has been edited !');

            return $this->redirectToRoute('app_task_show', ['taskId' => $task->getId()]);
        }

        return $this->render('task/edit.html.twig', compact('task', 'form'));
    }


    #[Route('task/{id<[0-9]+>}/delete', name: 'app_task_delete', methods: ["DELETE"])]
    public function delete(int $id, TaskRepository $taskRepo, Request $request): Response
    {
        $token = $request->request->get('_token');
        $task = $taskRepo->findOneBy(['id'=>$id]);

        if(!$this->isCsrfTokenValid('task_delete_' . $task->getId(), $token)) {
            throw  new \Exception('Invalid CSRF token.');
        }

        $taskRepo->remove($task, true);

        $this->addFlash('success', 'Task successfully deleted !');
        
        return $this->redirectToRoute('app_project_show', ['id' => $task->getProject()->getId()]);
    }

    #[Route('task/user', name: 'app_task_user', methods: ["GET"])]
    public function userTasks()
    {
        return $this->render('task/user.html.twig');
    }
}

templates/task/create.html.twig
{% extends 'base.html.twig' %}

{% block title %} Project #{{ projectId }} {% endblock %}
 
{% block body %}

<div class="max-w-md mx-auto">
    <div>
        <h1 class="p-2 text-center text-3xl italic underline font-bold">Create task</h1>
    </div>

    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" class="mt-4 w-full bg-orange-500 hover:bg-orange-600 text-white rounded shadow p-4 block" value="Create" formnovalidate />

    {{ form_end(form) }}
</div>

{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edit task "{{ task.name }}" {% endblock %}
 
{% block body %}

<div class="max-w-md mx-auto">
    <div>
        <h1 class="p-2 text-center text-3xl italic underline font-bold">Edit task</h1>
    </div>

    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" class="mt-4 w-full bg-orange-500 hover:bg-orange-600 text-white rounded shadow p-4 block" value="Edit" formnovalidate />

    {{ form_end(form) }}
</div>

{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ task.project.name }} - {{ task.name }} {% endblock %}

{% block body %}

<h1 class="p-2 text-center text-3xl italic underline font-bold">
    {{ task.project.name }}
</h1>

<div class="grid grid-cols-4">
    <div class="col-span-3">
        <div class="d-block drop-shadow-md m-3 p-3 shadow shadow-gray-400 rounded">
            <div class="flex grid-cols-2 gap-2">
                <h2 class="flex text-lg italic underline">{{ task.name }}</h2><span class="text-sm mt-1 mr-1 text-gray-400 align-baseline"> - Created by {{ task.author ? task.author.username : "Unknown" }}</span>
                <span class="grow text-right">
                    <span class="inline-block w-[110px] state state-{{ task.state.toString()|lower}} text-center">
                        {{ task.state.toString()}}
                    </span>
                </span>
            </div>
            <p class="ml-3 mt-3">{{ task.description }}</p>
        </div>

        {% for comment in task.comments %}
            <div class="ml-10 d-block drop-shadow-md m-3 p-2 shadow shadow-gray-400 rounded">
                <div class="grid grid-cols-2">
                    <p class="font-bold">
                        {{ comment.author ? comment.author.username : "Unknown" }}
                        <span class="text-sm mt-1 mr-1 text-gray-400 align-baseline font-normal"> 
                            on {{ comment.createdAt|date("F d, Y") }} at {{ comment.createdAt|date("H:i") }}
                            {% if comment.createdAt != comment.updatedAt %}
                                (edited on {{ comment.updatedAt|date("F d, Y") }} at {{ comment.updatedAt|date("H:i") }})
                            {% endif %}
                        </span>
                    </p>
                
                    <div class="grow grid-cols-3 text-right">
                        {% if app.user and app.user.username == comment.author.username %}
                            <a href="{{ path('app_comment_edit', {commentId: comment.id}) }}">
                                <button class="px-2 py-1 bg-orange-500 hover:bg-orange-600 text-white shadow shadow-gray-400 rounded">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </button>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <p class="mt-3">{{ comment.content }}</p>
            </div>
        {% endfor %}


        {% if app.user %}
            <div class="mt-10 mx-10">
                {{ form_start(form) }}
                    {{ form_row(form.content, {
                        label: 'Comment'
                    }) }}

                    <div class="grid grid-cols-8">
                        <button type="submit" class="mt-4 col-start-8 bg-orange-500 hover:bg-orange-600 text-white rounded shadow p-4 block">Send</button>
                    </div>
                {{ form_end(form) }}
            </div>
        {% endif %}
    </div>

    <div class="d-block drop-shadow-md m-3 p-2 shadow shadow-gray-400 rounded">

        <div class="grow text-right">
            <a href="{{ path('app_project_show', { 'id': task.project.id }) }}" class="underline text-orange-500 hover:text-orange-600">Back</a>
        </div>

        <p class="mt-3 text-lg underline">Assigned users :</p>

        {% if task.assignedUsers is empty %}
            <p class="ml-3">No users assigned to this task.</p>
        {% else %}
            {% for assignedUser in task.AssignedUsers %}
                <p class="ml-3">- {{ assignedUser.username }}</p>
            {% endfor %}
        {% endif %}
        
            <div class="text-right mt-5">
                {% if is_granted("ROLE_PROJECT_MANAGER") %}
                    <a href="{{ path('app_task_edit', {id: task.id}) }}" class="inline">
                        <button class="px-2 py-1 bg-orange-500 hover:bg-orange-600 text-white shadow shadow-gray-400 rounded">
                            <i class="fa-solid fa-pen-to-square"></i> Edit task
                        </button>
                    </a>
                {% endif %}

                {% if is_granted("ROLE_PROJECT_MANAGER") %}
                    <button class="px-2 py-1 bg-red-500 hover:bg-red-600 text-white shadow shadow-gray-400 rounded" onclick="event.preventDefault(); confirm('Are you sure ?') && document.getElementById('js-task-delete-form').submit();">
                        <i class="fa-solid fa-trash"></i> Delete task
                    </button>
                    <form id="js-task-delete-form" action="{{ path('app_task_delete', {id: task.id}) }}" method="POST" style="display: none">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('task_delete_' ~ task.id) }}" />
                    </form>
                {% endif %}
            </div>
    </div>

</div>


{% endblock %}

templates/task/user.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ app.user.username }}'s tasks {% endblock %}

{% block body %}

<h1 class="p-2 text-center text-3xl italic underline font-bold">
    Your tasks
</h1>

{% if app.user.assignedTasks|length > 0 %}
    {% for task in app.user.assignedTasks %}
        <a href="{{ path('app_task_show', { 'taskId': task.id }) }}">
            <div class="d-block drop-shadow-md m-3 p-3 shadow shadow-gray-400 rounded">
                <div class="text-sm text-slate-500 italic">
                    {{ task.project.name }}
                </div>
                <div class="flex grid-cols-2 gap-2">
                    <h2 class="flex text-lg italic underline">{{ task.name }}</h2><span class="text-sm mt-1 mr-1 text-gray-400 align-baseline"> - Created by {{ task.author ? task.author.username : "Unknown" }}</span>
                    <span class="grow text-right">
                        <span class="inline-block w-[110px] state state-{{ task.state.toString()|lower}} text-center">
                            {{ task.state.toString()}}
                        </span>
                    </span>
                </div>
                <p class="ml-3 mt-3">{{ task.description }}</p>
            </div>
        </a>
    {% endfor %}
{% else %}
    <p>No tasks were assigned to you.</p>
{% endif %}

{% endblock %}