src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: "projects")]
#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $presentation = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Task::class, orphanRemoval: true)]
    private Collection $tasks;

    #[ORM\ManyToOne(inversedBy: 'projects')]
    private ?User $project_manager = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'assignedProjects')]
    private Collection $team_members;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->team_members = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): static
    {
        $this->presentation = $presentation;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }

    public function getProjectManager(): ?User
    {
        return $this->project_manager;
    }

    public function setProjectManager(?User $project_manager): static
    {
        if(!in_array('ROLE_PROJECT_MANAGER', $project_manager->getRoles(), true))
        {
            throw new \Exception("This user isn't a project manager.");
        }

        $this->project_manager = $project_manager;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getTeamMembers(): Collection
    {
        return $this->team_members;
    }

    public function addTeamMember(User $teamMember): static
    {
        if (!$this->team_members->contains($teamMember)) {
            $this->team_members->add($teamMember);
        }

        return $this;
    }

    public function removeTeamMember(User $teamMember): static
    {
        $this->team_members->removeElement($teamMember);

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'constraints' => [
                    new NotBlank,
                    new Length(['min' => 3])
                ],
                
            ])
            ->add('presentation', TextareaType::class, [
                'constraints' => [
                    new NotBlank,
                    new Length(['min' => 15])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use App\Repository\UserRepository;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_home', methods: ["GET"])]
    public function index(ProjectRepository $projectRepo, Request $request): Response
    {
        if(!$this->getUser())
            return $this->redirectToRoute('app_projects');

        $pageName = "Your projects";
        $projects = $this->getUser()->getProjectsToDisplay();

        return $this->render('project/index.html.twig', compact('projects', 'pageName'));
    }

    #[Route('/projects', name: 'app_projects', methods: ["GET"])]
    public function showallProjects(ProjectRepository $projectRepo, Request $request): Response
    {
        $pageName = "Projects" ;
        $projects = $projectRepo->findAll();

        return $this->render('project/index.html.twig', compact('projects', 'pageName'));
    }

    #[Route('project/{id<[0-9]+>}', name: 'app_project_show', methods: ["GET"])]
    public function show(int $id, ProjectRepository $projectRepo): Response
    {
        $project = $projectRepo->find($id);

        return $this->render('project/show.html.twig',compact('project'));
    }

    #[Route('project/create', name: 'app_project_create', methods: ["GET", "POST"])]
    public function create(Request $request, ProjectRepository $projectRepo)
    {
        $form = $this->createForm(ProjectType::class);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $project  = $form->getData();

            $projectRepo->save($project, true);

            $this->addFlash('success', 'Project created !');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('project/create.html.twig', compact('form'));
    }

    #[Route('project/{id<[0-9]+>}/edit', name: 'app_project_edit', methods: ["GET", "PUT"])]
    public function edit(int $id, ProjectRepository $projectRepo, Request $request): Response
    {
        $project = $projectRepo->find($id);

        // TeamManagers can only edit the project manager assigned to the project
        if($this->isGranted('ROLE_TEAM_MANAGER'))
        {
            $form = $this->createFormBuilder($project)
                ->add('project_manager', EntityType::class, [
                    'class' => User::class,
                    'choice_label' => 'username',
                    'query_builder' => function(UserRepository $userRepo) {
                        return $userRepo->getProjectManagersQuery();
                    }
                ])
                ->setMethod("PUT")
                ->getForm();
        }
        // Else, ProjectManagers can edit all the project except the project manager assigned to the project
        else 
        {
            $form = $this->createForm(ProjectType::class, $project, ['method' => 'PUT']);
        }
        

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $projectRepo->save($project, true);

            $this->addFlash('success', 'The project has been edited !');
            
            return $this->redirectToRoute('app_project_show', [ 'id' => $project->getId() ]);
        }

        return $this->render('project/edit.html.twig',compact('project', 'form'));
    }

    #[Route('project/{id<[0-9]+>}/delete', name: 'app_project_delete', methods: ["DELETE"])]
    public function delete(int $id, ProjectRepository $projectRepo, Request $request): Response
    {
        $token = $request->request->get('_token');
        $project = $projectRepo->findOneBy(['id'=>$id]);

        if(!$this->isCsrfTokenValid('project_delete_' . $project->getId(), $token)) {
            throw  new \Exception('Invalid CSRF token.');
        }

        $projectRepo->remove($project, true);

        $this->addFlash('success', 'Project successfully deleted !');
        
        return $this->redirectToRoute('app_home');
    }

    


}

templates/project/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'Project #' %}

{% block body %}

<div class="max-w-md mx-auto">
    <div>
        <h1 class="p-2 text-center text-3xl italic underline font-bold">Create project</h1>
    </div>

    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" class="mt-4 w-full bg-orange-500 hover:bg-orange-600 text-white rounded shadow p-4 block" value="Create" formnovalidate />

    {{ form_end(form) }}
</div>

{% endblock %}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edit project {{ project.name }} {% endblock %}

{% block body %}

<div class="max-w-md mx-auto">
    <div>
        <h1 class="p-2 text-center text-3xl italic underline font-bold">Edit project</h1>
    </div>

    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" class="mt-4 w-full bg-orange-500 hover:bg-orange-600 text-white rounded shadow p-4 block" value="Edit" formnovalidate />

    {{ form_end(form) }}
</div>

{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Projects' %}

{% block body %}

<h1 class="p-2 text-center text-3xl italic underline font-bold">{{ pageName }}</h1>

<p class="text-center text-slate-700">Here is the full list of created projects : </p>

{% if projects|length > 0 %}
    {% for project in projects %}
        <a href="{{ path('app_project_show', {id: project.id}) }}">
            <div class="d-block drop-shadow-md m-3 p-2 shadow shadow-gray-400 rounded">
                <h2 class="inline text-lg italic underline">{{ project.name }} </h2>
                <span class="text-sm italic"> - Managed by {{ project.projectManager ? project.projectManager.username : "Unknown" }}</span>

                <p class="ml-3">{{ project.presentation }}</p>
            </div>
        </a>
    {% endfor %}
    
{% else %}
    <p>No projects are assigned to you.</p>
{% endif %}

{% if is_granted("ROLE_PROJECT_MANAGER") or is_granted("ROLE_TEAM_MANAGER") %}
    <div class="text-right">
        <a href="{{ path('app_project_create') }}" class="underline text-orange-500 hover:text-orange-600">
            + Add project
        </a>
    </div>
{% endif %}

{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title 'Project #' %}

{% block body %}

<h1 class="p-2 text-center text-3xl italic underline font-bold">
    {{ project.name }}
</h1>

<div class="grid grid-cols-4">
    <div class="col-span-3">
        <p>
            {{ project.presentation }}
        </p>

        {% for task in project.tasks %}
            <a href="{{ path('app_task_show', {'taskId': task.id}) }}">
                <div class="d-block drop-shadow-md m-3 p-2 shadow shadow-gray-400 rounded">
                    <div class="flex grid-cols-2 gap-2">
                        <h2 class="flex text-lg italic underline">{{ task.name }}</h2>
                        <span class="text-sm mt-1 mr-1 text-gray-400 align-baseline"> 
                            - Created by {{ task.author ? task.author.username : "Unknown" }} 
                            on {{ task.createdAt|date("F d, Y") }}
                            {% if task.createdAt|date("F d, Y") != task.updatedAt|date("F d, Y") %}
                                (edited on {{ task.updatedAt|date("F d, Y") }})
                            {% endif %}
                        </span>
                        <span class="grow text-right">
                            <span class="inline-block w-[110px] state state-{{ task.state.toString()|lower}} text-center">
                                {{ task.state.toString()}}
                            </span>
                        </span>
                    </div>
                    <p class="ml-3">{{ task.description }}</p>
                </div>
            </a>
        {% endfor %}
        
    </div>

    <div class="d-block drop-shadow-md m-3 p-2 shadow shadow-gray-400 rounded">

        <div class="grow text-right">
            <a href="{{ path('app_home') }}" class="underline text-orange-500 hover:text-orange-600">Back</a>
        </div>

        <p class="mt-3 text-lg underline">Team members :</p>

        {% if project.teamMembers is empty %}
            <p class="ml-3">No team assigned to this project.</p>
        {% else %}
            {% for teamMember in project.teamMembers %}
                <p class="ml-3">- {{ teamMember.username }}</p>
            {% endfor %}
        {% endif %}
        
        <div class="text-right mt-5">
            {% if is_granted("ROLE_PROJECT_MANAGER") %}
                <div class="inline text-right">
                    <a href="{{ path('app_task_create', {'id': project.id }) }}" class="inline">
                        <button class="px-2 py-1 bg-orange-500 hover:bg-orange-600 text-white shadow shadow-gray-400 rounded">
                            <i class="fa-solid fa-plus"></i> Add task
                        </button>
                    </a>
                </div>
            {% endif %}

            {% if is_granted("ROLE_PROJECT_MANAGER") or is_granted("ROLE_TEAM_MANAGER") %}
                <a href="{{ path('app_project_edit', {id: project.id}) }}" class="inline">
                    <button class="px-2 py-1 bg-orange-500 hover:bg-orange-600 text-white shadow shadow-gray-400 rounded">
                        <i class="fa-solid fa-pen-to-square"></i> Edit project
                    </button>
                </a>
            {% endif %}

            {% if is_granted("ROLE_TEAM_MANAGER") %}
                <button class="px-2 py-1 bg-red-500 hover:bg-red-600 text-white shadow shadow-gray-400 rounded" onclick="event.preventDefault(); confirm('Are you sure ?') && document.getElementById('js-project-delete-form').submit();">
                    <i class="fa-solid fa-trash"></i> Delete project
                </button>
                <form id="js-project-delete-form" action="{{ path('app_project_delete', {id: project.id}) }}" method="POST" style="display: none">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('project_delete_' ~ project.id) }}" />
                </form>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}